name: 构建容器镜像

on:
  workflow_dispatch: # 手动触发
  push:

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE: ${{ vars.IMAGE }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 这里用于定义 GITHUB_TOKEN 的权限
    permissions:
      packages: write
      contents: read

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: 设置环境变量
        run: |
          echo "GIT_TAG_VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//')" >> $GITHUB_ENV
          echo "REGISTRY_USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "VERSION=$(jq -c . < version.json)" >> $GITHUB_ENV
          echo "PG_MAJOR_VERSION=$(jq -r '.postgre' version.json | cut -d'.' -f1)" >> $GITHUB_ENV

      - name: 检查环境变量
        run: |
          echo "REGISTRY:           ${{ env.REGISTRY }}"
          echo "REGISTRY_USERNAME:  ${{ env.REGISTRY_USERNAME }}"
          echo "IMAGE:              ${{ env.IMAGE }}"
          echo "GIT_TAG_VERSION:    ${{ env.GIT_TAG_VERSION }}"
          echo "VERSION:            ${{ env.VERSION }}"
          echo "PG_MAJOR_VERSION:   ${{ env.PG_MAJOR_VERSION }}"

      # 配置 QEMU 和 buildx 用于多架构镜像的构建
      - name: 配置 QEMU 环境
        uses: docker/setup-qemu-action@v3

      - name: 配置容器环境
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 检查构建器
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      # 缓存 Docker 镜像以加速构建
      - name: 配置容器缓存层
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 登录容器注册表
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 根据输入自动生成 tag 和 label 等数据
      - name: 构建容器元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=sha
            type=raw,value=latest
            type=raw,value=${{ fromJson(env.VERSION).postgre }}

      - name: 检查容器元数据
        run: |
          echo "docker iamge version: ${{ steps.meta.outputs.version }}"
          echo ""
          echo "docker iamge tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "docker iamge labels:"
          echo "${{ steps.meta.outputs.labels }}"

      - name: 构建容器并推送注册表
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: |
            linux/arm64
            linux/amd64
          outputs: type=registry,push=true,compression=gzip,compression-level=9
          provenance: false
          build-args: |
            PG_VERSION=${{ fromJson(env.VERSION).postgre }}
            PG_MAJOR_VERSION=${{ env.PG_MAJOR_VERSION }}
            PGVECTORS_VERSION=${{ fromJson(env.VERSION).plugin.pgvecto_rs }}
            PGVECTOR_VERSION=${{ fromJson(env.VERSION).plugin.pgvector }}
            TSDB_VERSION=${{ fromJson(env.VERSION).plugin.timescaledb }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: 检查镜像
        run: |
          docker buildx imagetools inspect \
          ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.meta.outputs.version }}
